# Generated by Django 5.2.1 on 2026-03-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='categoria',
            field=models.CharField(choices=[('SOFTWARE', 'Desarrollo de Software'), ('INGLES', 'Aprendizaje de Inglés'), ('OTRO', 'Otras tareas')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
