# Generated by Django 5.2.1 on 2026-03-12 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_profile_alter_category_options_alter_task_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='agenda_task_user_id_568beb_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='notificacion_enviada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'is_completed', 'notificacion_enviada'], name='agenda_task_user_id_eb10e6_idx'),
        ),
    ]
