# Generated by Django 5.2.1 on 2026-03-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_remove_task_agenda_task_user_id_568beb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='minutes_before',
            field=models.PositiveIntegerField(default=15, help_text='¿Cuántos minutos antes quieres el aviso?'),
        ),
    ]
